Imported copy in packet as it was used with change 036db63fb2a4
The test would fail becase copy was not imported:

$ python fields.py
**********************************************************************
File "fields.py", line 782, in __main__.ByteLenField
Failed example:
    p = Foo()/'some payload'
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.ByteLenField[2]>", line 1, in <module>
        p = Foo()/'some payload'
      File "/home/muelli/hg/scapy/scapy/base_classes.py", line 198, in __call__
        i.__init__(*args, **kargs)
      File "/home/muelli/hg/scapy/scapy/packet.py", line 75, in __init__
        self.init_fields()
      File "/home/muelli/hg/scapy/scapy/packet.py", line 92, in init_fields
        self.do_init_fields(self.fields_desc)
      File "/home/muelli/hg/scapy/scapy/packet.py", line 96, in do_init_fields
        self.default_fields[f.name] = copy.deepcopy(f.default)
    NameError: global name 'copy' is not defined
**********************************************************************